name: "Pull Request Docs Check and invoke sphinx-build"
on: 
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "doc/"
        build-command: "sphinx-build -b html . _build"
